### ISSUE TITLE
could you send me your paper?

### ISSUE THREAD

**Issue by Zhang-O** [JianshuZhang/TreeDecoder#1]
I could find your paper through google scholar.

Another paper "Radical analysis network for learning hierarchies of Chinese characters" , I also searched a lot in google, but had no access to it.

Could you send the papers above to my mail address : 691259192@qq.com
Thanks a lot!

**Comment by JianshuZhang** [comment]
I have uploaded the ICML paper. But I may have no right to release the RAN paper, as it is a journal paper and has been published.

**Comment by Zhang-O** [comment]
yeh, it's not appropriate that you release a journal paper publicly without its copyright . 
But sending it personally without business purpse is ok!
OK, forget it. I 'll wait.
Thanks for job!!!
