### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by Nateliu712** [JianshuZhang/TreeDecoder#2]
Hi,jianshu!
I am pursuing your paper and trying to  re-produce your work , i have some questions.
1. what is "106_dictionary.txt", "jiaming-train-py3.pkl" etc. ? Where can i get such a file?
2. how to convert lg file to the training format and convert recognition result to latex?
3. the time you spend on training and testing with single Nvidia Tesla V100

Thanks

**Comment by JianshuZhang** [comment]
1. The data hasn't been prepared, will get it done after the conference.
2. use the latex2gtd.py to convert latex to training format, and use the gtd2latex to convert recognition result to latex
3. using V100, the training costs about 48h, the testing costs about 5min on CROHME 2014 (986 samples).

**Comment by Nateliu712** [comment]
> 1. The data hasn't been prepared, will get it done after the conference.
> 2. use the latex2gtd.py to convert latex to training format, and use the gtd2latex to convert recognition result to latex
> 3. using V100, the training costs about 48h, the testing costs about 5min on CROHME 2014 (986 samples).

Thanks for your reply，i'm sorry  to brother again. i use the data in WAP, and run latex2gtd.py convert latex to training format. however when i run the train.sh shell to train the model, I meet a problem, here is the log,
/opt/conda/conda-bld/pytorch_1570910687650/work/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [0,0,0], thread: [123,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1570910687650/work/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [0,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1570910687650/work/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [0,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1570910687650/work/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [0,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1570910687650/work/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [0,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "train_wap.py", line 185, in <module>
    WAP_model(params, x, x_mask, ly, ly_mask, ry, ry_mask, re, re_mask, ma, ma_mask, lp, rp)
  File "/data/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/code/TreeDecoder-master/codes/encoder_decoder.py", line 106, in forward
    lemb, Pemb, remb = self.emb_model(params, ly, lp, ry)  # (seqs_y,batch,m)
  File "/data/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/code/TreeDecoder-master/codes/encoder_decoder.py", line 56, in forward
    remb_shifted = torch.zeros([remb.shape[0], remb.shape[1], params['m']], dtype=torch.float32).cuda()
RuntimeError: CUDA error: device-side assert triggered
how can i fix this problem?

**Comment by Nateliu712** [comment]
hi,jianshu,
i found the reason for this error. i convert latex to gtd with latex2gtd.py script and get 107 vocabs(105 token and <s> </s>), and 8 relations(above, blow, right, inside,sup,sub,start and end). however you have 106 vocabs(params['K'] = 106) and 7 relations(params['Kre'] = 7). am i doing something wrong?

**Comment by JianshuZhang** [comment]
The error can be settled by setting params[k]=107 and params[kre]=8. I set relations to be 7 because I remove the relation “end”, as relation “end” appears at the last decoding step, so it is not necessary to be recognized, so as the relation “start”. But it is ok for you to include “end” in the relation dictionary, no difference. But you have to change the params[k] to your size of dictionary, and params[kre] to your size of relation dictionary.

**Comment by Nateliu712** [comment]
hi,jianshu
i have a question about the training data align_gtd.pkl. I understand that the alignment is the matrix that aligns the parent node and the child node. for example，a gtd file is
\frac     1   sos     0   Start
1           2   \frac   1   Above
9           3   \frac   1   Below
eos     4   9        3   End

the alignment matrix is a 4*4 matrix
0 1 1 0
0 0 0 0
0 0 0 1 
0 0 0 0
Am i understanding right？

**Comment by JianshuZhang** [comment]
almost right, it should be
1 0 0 0
0 1 1 0
0 0 0 0
0 0 0 1
