### ISSUE TITLE
Question about the necessity of the memory based attention

### ISSUE THREAD

**Issue by lai-agent-m** [JianshuZhang/TreeDecoder#4]
I read the paper and I believe I understand your motivation to add the memory based attention.
For the example you shown on the paper
x+x^{2} which has tree struct:
```
x	1	<s>	0	Start
+	2	x	1	Right
x	3	+	2	Right
2	4	x	3	Sup
</s>	5	2	4	End
```
even if we get rid of all the orders which gives me the tree:
```
x	<s>	Start
+	x	Right
x	+	Right
2	x	Sup
</s>	2	End
```
In the paper you states that the tree also represents x ^{2} + x so there's ambiguity. but if we assume the right parent is the closest 'valid' child, the latex correspond to this tree must be x+x^{2}

With a more complicated example

for latex '\\frac { 2 6 7 + \\frac { 1 1 } { 2 2 } } { 3 }'
With your script I get 
```
\frac	1	<s>	0	Start
2	2	\frac	1	Above
6	3	2	2	Right
7	4	6	3	Right
+	5	7	4	Right
\frac	6	+	5	Right
1	7	\frac	6	Above
1	8	1	7	Right
2	9	\frac	6	Below
2	10	2	9	Right
3	11	\frac	1	Below
</s>	12	3	11	End
```

If I get rid of the order indexes
```
\frac	<s>	Start     0
2	\frac	Above   1
6	2	Right     2
7	6	Right     3 
+	7	Right     4
\frac	+	Right     5
1	\frac	Above   6
1	1	Right     7
2	\frac	Below    8
2	2	Right      9
3	\frac	Below    10
</s>	3	End        11
```

There's no ambiguity in this tree also, 
The rule is to pick the closest 'valid' child. For different children there are different rules to decide if the child is valid.
Fraction must have one and only one above and one and only one below, and above is always before below. With those rules we are able to decide if a frac is valid.
(If the output tree do not obey this rules ex one tree's frac has only above but no below. we can simply say the result is not valid)
For line 1 there is only 1 frac so no problem.
For line 6 it's relation is above and above for frac in line 0 is already taken. We can already conclude the frac in line 5 is the only choice. Furthermore the frac in line 5 is closer to line 6.
For line 8 frac in line 5 is the closer frac.
For line 10, because both the above and below for frac in line 5 are picked. only frac in line 0 is the possible choice.

I believe those orders are forced on training stage. so we can expect the model to output the tree in same order. I wonder if I misunderstood something or the assumption I made is not valid in some special cases.
Thanks,

**Comment by JianshuZhang** [comment]
Very good question!
Your example is right, but your example is ideal. Think about that, if your model recognize \frac as - (minus operation or somewhat other math symbols), your rule may not be robust. So, in these bad cases, I believe using a memory attention is more robust than only trusting recognition results.
What do you think?

**Comment by lai-agent-m** [comment]
I'm not sure if memory attention is able to correct those samples.
I guess we can do an empirical experiment to check if memory attention increase the score.
To do the evaluation we need to at least have a script that translates the trees to latex without the index information.

I feel that the index information do not contribute to the following time steps, I didn't read the inference part carefully yet. If that's true we only need one more script, then we compare the accuracy of recovered latexes. Otherwise we may need a new model to do the experiment.

**Comment by JianshuZhang** [comment]
Good suggestion! If I find it is doable, I will try it and release one inference version.

**Comment by lai-agent-m** [comment]
Okay when I try to implement an convert back file I found an example when order is necessary
```
2 2 Superscription
2 2 Right
2 2 Right 
+ 2 Right
3 + Right
```

it can be 2 ^ { 2 2 }  + 3
or 2 ^ { 2 2 + 3 }
or 2 ^ { 2 } 2 + 3
The ambiguity is mainly caused by the fact that ^ is represented by relationship.
I really like your idea but I feel that the tree structure can still be polished. I will try to define new tree structures and modify attention mechanism correspondently

**Comment by JianshuZhang** [comment]
Good!
Yes, the tree decoder can still be polished, we are working on it. Welcome to have a discussion together.
